import { Router, Request, Response } from 'express';
import { authenticate } from '../middlewares/auth.middleware';

const router = Router();

// ── Dados dos times (1382 times do Excel) ──────────────────────────────────
// Gerado automaticamente a partir do arquivo Excel
const ALL_TEAMS: { id: number; name: string; group: string }[] = [
  // Times - Aleatórios
  {id:1,name:"Israel - Ashdod",group:"Aleatórios"},{id:2,name:"Israel - B Jerusalem",group:"Aleatórios"},{id:3,name:"Israel - Bnei Yehuda",group:"Aleatórios"},{id:4,name:"Israel - H Akko",group:"Aleatórios"},{id:5,name:"Israel - H Beer Sheva",group:"Aleatórios"},{id:6,name:"Israel - H Haifa",group:"Aleatórios"},{id:7,name:"Israel - H Jerusalem",group:"Aleatórios"},{id:8,name:"Israel - H Tel Aviv",group:"Aleatórios"},{id:9,name:"Israel - Ironi Kiryat Shmona",group:"Aleatórios"},{id:10,name:"Israel - M Haifa",group:"Aleatórios"},{id:11,name:"Israel - M Tel Aviv",group:"Aleatórios"},{id:12,name:"Israel - Ness Ziona",group:"Aleatórios"},{id:13,name:"Israel - Sakhnin",group:"Aleatórios"},{id:14,name:"Israel - Sektzia Nes Tziona",group:"Aleatórios"},
  // Times - Alemanha
  {id:100,name:"Arminia Bielefeld",group:"Alemanha"},{id:101,name:"Augsburg",group:"Alemanha"},{id:102,name:"Bayern Munich",group:"Alemanha"},{id:103,name:"Bochum",group:"Alemanha"},{id:104,name:"Borussia Dortmund",group:"Alemanha"},{id:105,name:"Borussia M'gladbach",group:"Alemanha"},{id:106,name:"Darmstadt",group:"Alemanha"},{id:107,name:"Dusseldorf",group:"Alemanha"},{id:108,name:"Eintracht Frankfurt",group:"Alemanha"},{id:109,name:"FC Koln",group:"Alemanha"},{id:110,name:"Freiburg",group:"Alemanha"},{id:111,name:"Greuther Furth",group:"Alemanha"},{id:112,name:"Heidenheim",group:"Alemanha"},{id:113,name:"Hertha BSC",group:"Alemanha"},{id:114,name:"Hoffenheim",group:"Alemanha"},{id:115,name:"Holstein Kiel",group:"Alemanha"},{id:116,name:"Kaiserslautern",group:"Alemanha"},{id:117,name:"Karlsruher SC",group:"Alemanha"},{id:118,name:"Leverkusen",group:"Alemanha"},{id:119,name:"Mainz",group:"Alemanha"},{id:120,name:"Nurnberg",group:"Alemanha"},{id:121,name:"Paderborn",group:"Alemanha"},{id:122,name:"RB Leipzig",group:"Alemanha"},{id:123,name:"Schalke 04",group:"Alemanha"},{id:124,name:"SpVgg Greuther Furth",group:"Alemanha"},{id:125,name:"St. Pauli",group:"Alemanha"},{id:126,name:"Stuttgart",group:"Alemanha"},{id:127,name:"Union Berlin",group:"Alemanha"},{id:128,name:"Werder Bremen",group:"Alemanha"},{id:129,name:"Wolfsburg",group:"Alemanha"},
  // Times - Brasil
  {id:200,name:"3B da Amazonia - Fem",group:"Brasil"},{id:201,name:"ABC",group:"Brasil"},{id:202,name:"América MG",group:"Brasil"},{id:203,name:"Amazonas",group:"Brasil"},{id:204,name:"Athletico Paranaense",group:"Brasil"},{id:205,name:"Atlético Mineiro",group:"Brasil"},{id:206,name:"Bahia",group:"Brasil"},{id:207,name:"Botafogo",group:"Brasil"},{id:208,name:"Bragantino",group:"Brasil"},{id:209,name:"Ceará",group:"Brasil"},{id:210,name:"Corinthians",group:"Brasil"},{id:211,name:"Coritiba",group:"Brasil"},{id:212,name:"Cruzeiro",group:"Brasil"},{id:213,name:"CSA",group:"Brasil"},{id:214,name:"Cuiabá",group:"Brasil"},{id:215,name:"Flamengo",group:"Brasil"},{id:216,name:"Fluminense",group:"Brasil"},{id:217,name:"Fortaleza",group:"Brasil"},{id:218,name:"Goiás",group:"Brasil"},{id:219,name:"Grêmio",group:"Brasil"},{id:220,name:"Internacional",group:"Brasil"},{id:221,name:"Juventude",group:"Brasil"},{id:222,name:"Náutico",group:"Brasil"},{id:223,name:"Palmeiras",group:"Brasil"},{id:224,name:"Santos",group:"Brasil"},{id:225,name:"São Paulo",group:"Brasil"},{id:226,name:"Sport Recife",group:"Brasil"},{id:227,name:"Tombense",group:"Brasil"},{id:228,name:"Vasco da Gama",group:"Brasil"},{id:229,name:"Vitória",group:"Brasil"},
  // Times - Argentina
  {id:300,name:"Agropecuario",group:"Argentina"},{id:301,name:"Aldosivi",group:"Argentina"},{id:302,name:"All Boys",group:"Argentina"},{id:303,name:"Almagro",group:"Argentina"},{id:304,name:"Almirante Brown",group:"Argentina"},{id:305,name:"Banfield",group:"Argentina"},{id:306,name:"Belgrano",group:"Argentina"},{id:307,name:"Boca Juniors",group:"Argentina"},{id:308,name:"Chacarita Juniors",group:"Argentina"},{id:309,name:"Colón",group:"Argentina"},{id:310,name:"Defensa y Justicia",group:"Argentina"},{id:311,name:"Estudiantes",group:"Argentina"},{id:312,name:"Godoy Cruz",group:"Argentina"},{id:313,name:"Huracán",group:"Argentina"},{id:314,name:"Independiente",group:"Argentina"},{id:315,name:"Lanús",group:"Argentina"},{id:316,name:"Newell's Old Boys",group:"Argentina"},{id:317,name:"Platense",group:"Argentina"},{id:318,name:"Racing Club",group:"Argentina"},{id:319,name:"River Plate",group:"Argentina"},{id:320,name:"Rosario Central",group:"Argentina"},{id:321,name:"San Lorenzo",group:"Argentina"},{id:322,name:"San Martín",group:"Argentina"},{id:323,name:"Talleres",group:"Argentina"},{id:324,name:"Tigre",group:"Argentina"},{id:325,name:"Unión",group:"Argentina"},{id:326,name:"Vélez Sarsfield",group:"Argentina"},
  // Times - Espanha
  {id:400,name:"Alaves",group:"Espanha"},{id:401,name:"Albacete",group:"Espanha"},{id:402,name:"Almeria",group:"Espanha"},{id:403,name:"Amorebieta",group:"Espanha"},{id:404,name:"Athletic Bilbao",group:"Espanha"},{id:405,name:"Atletico de Madrid",group:"Espanha"},{id:406,name:"Barcelona",group:"Espanha"},{id:407,name:"Betis",group:"Espanha"},{id:408,name:"Cadiz",group:"Espanha"},{id:409,name:"Celta Vigo",group:"Espanha"},{id:410,name:"Deportivo Alaves",group:"Espanha"},{id:411,name:"Elche",group:"Espanha"},{id:412,name:"Espanyol",group:"Espanha"},{id:413,name:"Getafe",group:"Espanha"},{id:414,name:"Girona",group:"Espanha"},{id:415,name:"Granada",group:"Espanha"},{id:416,name:"Las Palmas",group:"Espanha"},{id:417,name:"Leganés",group:"Espanha"},{id:418,name:"Levante",group:"Espanha"},{id:419,name:"Mallorca",group:"Espanha"},{id:420,name:"Osasuna",group:"Espanha"},{id:421,name:"Rayo Vallecano",group:"Espanha"},{id:422,name:"Real Madrid",group:"Espanha"},{id:423,name:"Real Sociedad",group:"Espanha"},{id:424,name:"Sevilla",group:"Espanha"},{id:425,name:"Valencia",group:"Espanha"},{id:426,name:"Valladolid",group:"Espanha"},{id:427,name:"Villarreal",group:"Espanha"},
  // Times - Inglaterra
  {id:500,name:"Arsenal",group:"Inglaterra"},{id:501,name:"Aston Villa",group:"Inglaterra"},{id:502,name:"Birningham - Eng",group:"Inglaterra"},{id:503,name:"Blackburn",group:"Inglaterra"},{id:504,name:"Brentford",group:"Inglaterra"},{id:505,name:"Brighton",group:"Inglaterra"},{id:506,name:"Burnley",group:"Inglaterra"},{id:507,name:"Chelsea",group:"Inglaterra"},{id:508,name:"Crystal Palace",group:"Inglaterra"},{id:509,name:"Everton",group:"Inglaterra"},{id:510,name:"Fulham",group:"Inglaterra"},{id:511,name:"Huddersfield",group:"Inglaterra"},{id:512,name:"Leeds United",group:"Inglaterra"},{id:513,name:"Leicester City",group:"Inglaterra"},{id:514,name:"Liverpool",group:"Inglaterra"},{id:515,name:"Luton Town",group:"Inglaterra"},{id:516,name:"Manchester City",group:"Inglaterra"},{id:517,name:"Manchester United",group:"Inglaterra"},{id:518,name:"Middlesbrough",group:"Inglaterra"},{id:519,name:"Newcastle",group:"Inglaterra"},{id:520,name:"Nottingham Forest",group:"Inglaterra"},{id:521,name:"Sheffield United",group:"Inglaterra"},{id:522,name:"Southampton",group:"Inglaterra"},{id:523,name:"Tottenham",group:"Inglaterra"},{id:524,name:"West Ham",group:"Inglaterra"},{id:525,name:"Wolves",group:"Inglaterra"},
  // Times - Italia
  {id:600,name:"AC Milan",group:"Itália"},{id:601,name:"Ascoli",group:"Itália"},{id:602,name:"Atalanta",group:"Itália"},{id:603,name:"Bari",group:"Itália"},{id:604,name:"Benevento",group:"Itália"},{id:605,name:"Bologna",group:"Itália"},{id:606,name:"Cagliari",group:"Itália"},{id:607,name:"Como",group:"Itália"},{id:608,name:"Cremonese",group:"Itália"},{id:609,name:"Empoli",group:"Itália"},{id:610,name:"Fiorentina",group:"Itália"},{id:611,name:"Frosinone",group:"Itália"},{id:612,name:"Genoa",group:"Itália"},{id:613,name:"Hellas Verona",group:"Itália"},{id:614,name:"Inter de Milão",group:"Itália"},{id:615,name:"Juventus",group:"Itália"},{id:616,name:"Lazio",group:"Itália"},{id:617,name:"Lecce",group:"Itália"},{id:618,name:"Monza",group:"Itália"},{id:619,name:"Napoli",group:"Itália"},{id:620,name:"Palermo",group:"Itália"},{id:621,name:"Parma",group:"Itália"},{id:622,name:"Roma",group:"Itália"},{id:623,name:"Salernitana",group:"Itália"},{id:624,name:"Sampdoria",group:"Itália"},{id:625,name:"Sassuolo",group:"Itália"},{id:626,name:"Torino",group:"Itália"},{id:627,name:"Udinese",group:"Itália"},{id:628,name:"Venezia",group:"Itália"},
  // Times - França
  {id:700,name:"AC Ajaccio",group:"França"},{id:701,name:"Amiens SC",group:"França"},{id:702,name:"Angers",group:"França"},{id:703,name:"Auxerre",group:"França"},{id:704,name:"Bastia",group:"França"},{id:705,name:"Brest",group:"França"},{id:706,name:"Clermont",group:"França"},{id:707,name:"Grenoble Foot",group:"França"},{id:708,name:"Lens",group:"França"},{id:709,name:"Lille",group:"França"},{id:710,name:"Lorient",group:"França"},{id:711,name:"Lyon",group:"França"},{id:712,name:"Marseille",group:"França"},{id:713,name:"Metz",group:"França"},{id:714,name:"Monaco",group:"França"},{id:715,name:"Montpellier",group:"França"},{id:716,name:"Nantes",group:"França"},{id:717,name:"Nice",group:"França"},{id:718,name:"Paris FC",group:"França"},{id:719,name:"Paris Saint-Germain",group:"França"},{id:720,name:"Reims",group:"França"},{id:721,name:"Rennes",group:"França"},{id:722,name:"Strasbourg",group:"França"},{id:723,name:"Toulouse",group:"França"},{id:724,name:"Troyes",group:"França"},
  // Times - Portugal
  {id:800,name:"Académico Viseu",group:"Portugal"},{id:801,name:"Arouca",group:"Portugal"},{id:802,name:"AVS",group:"Portugal"},{id:803,name:"Benfica",group:"Portugal"},{id:804,name:"Benfica B",group:"Portugal"},{id:805,name:"Braga",group:"Portugal"},{id:806,name:"Estoril Praia",group:"Portugal"},{id:807,name:"Famalicão",group:"Portugal"},{id:808,name:"FC Porto",group:"Portugal"},{id:809,name:"Gil Vicente",group:"Portugal"},{id:810,name:"Moreirense",group:"Portugal"},{id:811,name:"Paços de Ferreira",group:"Portugal"},{id:812,name:"Rio Ave",group:"Portugal"},{id:813,name:"Santa Clara",group:"Portugal"},{id:814,name:"Sporting CP",group:"Portugal"},{id:815,name:"Vizela",group:"Portugal"},
  // Times - Holanda
  {id:900,name:"Ajax",group:"Holanda"},{id:901,name:"Alkmaar",group:"Holanda"},{id:902,name:"Almere City FC",group:"Holanda"},{id:903,name:"Breda",group:"Holanda"},{id:904,name:"Cambuur",group:"Holanda"},{id:905,name:"Feyenoord",group:"Holanda"},{id:906,name:"Go Ahead Eagles",group:"Holanda"},{id:907,name:"Groningen",group:"Holanda"},{id:908,name:"Heerenveen",group:"Holanda"},{id:909,name:"PSV Eindhoven",group:"Holanda"},{id:910,name:"Twente",group:"Holanda"},{id:911,name:"Utrecht",group:"Holanda"},{id:912,name:"Vitesse",group:"Holanda"},
  // Times - México
  {id:1000,name:"Alebrijes Oaxaca",group:"México"},{id:1001,name:"Atl Morelia",group:"México"},{id:1002,name:"Atlas",group:"México"},{id:1003,name:"Atletico La Paz",group:"México"},{id:1004,name:"Chivas",group:"México"},{id:1005,name:"Club América",group:"México"},{id:1006,name:"Cruz Azul",group:"México"},{id:1007,name:"FC Juárez",group:"México"},{id:1008,name:"Mazatlán",group:"México"},{id:1009,name:"Monterrey",group:"México"},{id:1010,name:"Necaxa",group:"México"},{id:1011,name:"Pachuca",group:"México"},{id:1012,name:"PUMAS UNAM",group:"México"},{id:1013,name:"Querétaro",group:"México"},{id:1014,name:"Santos Laguna",group:"México"},{id:1015,name:"Tigres UANL",group:"México"},{id:1016,name:"Tijuana",group:"México"},{id:1017,name:"Toluca",group:"México"},
  // Times - EUA
  {id:1100,name:"Atlanta Utd",group:"EUA"},{id:1101,name:"Austin FC",group:"EUA"},{id:1102,name:"Birningham - EUA",group:"EUA"},{id:1103,name:"CF Montreal",group:"EUA"},{id:1104,name:"Charleston",group:"EUA"},{id:1105,name:"Chicago Fire",group:"EUA"},{id:1106,name:"Colorado Rapids",group:"EUA"},{id:1107,name:"Columbus Crew",group:"EUA"},{id:1108,name:"D.C. United",group:"EUA"},{id:1109,name:"FC Cincinnati",group:"EUA"},{id:1110,name:"FC Dallas",group:"EUA"},{id:1111,name:"Houston Dynamo",group:"EUA"},{id:1112,name:"Inter Miami",group:"EUA"},{id:1113,name:"L.A. Galaxy",group:"EUA"},{id:1114,name:"LAFC",group:"EUA"},{id:1115,name:"Minnesota United",group:"EUA"},{id:1116,name:"Nashville SC",group:"EUA"},{id:1117,name:"New England Revolution",group:"EUA"},{id:1118,name:"New York City FC",group:"EUA"},{id:1119,name:"New York Red Bulls",group:"EUA"},{id:1120,name:"Orlando City",group:"EUA"},{id:1121,name:"Philadelphia Union",group:"EUA"},{id:1122,name:"Portland Timbers",group:"EUA"},{id:1123,name:"Real Salt Lake",group:"EUA"},{id:1124,name:"San Jose Earthquakes",group:"EUA"},{id:1125,name:"Seattle Sounders",group:"EUA"},{id:1126,name:"Sporting Kansas City",group:"EUA"},{id:1127,name:"St. Louis City SC",group:"EUA"},{id:1128,name:"Toronto FC",group:"EUA"},{id:1129,name:"Vancouver Whitecaps",group:"EUA"},
  // Times - Chile
  {id:1200,name:"Antofagasta",group:"Chile"},{id:1201,name:"Arica",group:"Chile"},{id:1202,name:"Audax Italiano",group:"Chile"},{id:1203,name:"Barnechea",group:"Chile"},{id:1204,name:"CD Santa Cruz",group:"Chile"},{id:1205,name:"Cobreloa",group:"Chile"},{id:1206,name:"Colo-Colo",group:"Chile"},{id:1207,name:"Copiapó",group:"Chile"},{id:1208,name:"Curicó Unido",group:"Chile"},{id:1209,name:"Deportes Concepción",group:"Chile"},{id:1210,name:"Deportes Iquique",group:"Chile"},{id:1211,name:"Deportes La Serena",group:"Chile"},{id:1212,name:"Everton",group:"Chile"},{id:1213,name:"Huachipato",group:"Chile"},{id:1214,name:"La Calera",group:"Chile"},{id:1215,name:"Magallanes",group:"Chile"},{id:1216,name:"Melipilla",group:"Chile"},{id:1217,name:"O'Higgins",group:"Chile"},{id:1218,name:"Santiago Morning",group:"Chile"},{id:1219,name:"Santiago Wanderers",group:"Chile"},{id:1220,name:"Universidad Católica",group:"Chile"},{id:1221,name:"Universidad de Chile",group:"Chile"},
  // Times - Colombia
  {id:1300,name:"Aguilas",group:"Colômbia"},{id:1301,name:"América de Cali",group:"Colômbia"},{id:1302,name:"Atletico FC - Colombia",group:"Colômbia"},{id:1303,name:"Atletico Junior",group:"Colômbia"},{id:1304,name:"Atletico Nacional",group:"Colômbia"},{id:1305,name:"Bucaramanga",group:"Colômbia"},{id:1306,name:"Deportes Tolima",group:"Colômbia"},{id:1307,name:"Deportivo Cali",group:"Colômbia"},{id:1308,name:"Envigado",group:"Colômbia"},{id:1309,name:"La Equidad",group:"Colômbia"},{id:1310,name:"Millonarios",group:"Colômbia"},{id:1311,name:"Once Caldas",group:"Colômbia"},{id:1312,name:"Patriotas",group:"Colômbia"},{id:1313,name:"Peñarol - Colombia",group:"Colômbia"},{id:1314,name:"Santa Fe",group:"Colômbia"},
  // Times - Peru
  {id:1400,name:"AD Cantolão",group:"Peru"},{id:1401,name:"ADT Tarma",group:"Peru"},{id:1402,name:"Alfonso Ugarte",group:"Peru"},{id:1403,name:"Alianza Atlético",group:"Peru"},{id:1404,name:"Alianza Huanuco",group:"Peru"},{id:1405,name:"Alianza Lima",group:"Peru"},{id:1406,name:"Binacional",group:"Peru"},{id:1407,name:"Cajamarca",group:"Peru"},{id:1408,name:"Cienciano",group:"Peru"},{id:1409,name:"Cusco FC",group:"Peru"},{id:1410,name:"Deportivo Llacuabamba",group:"Peru"},{id:1411,name:"Deportivo Municipal",group:"Peru"},{id:1412,name:"FBC Melgar",group:"Peru"},{id:1413,name:"Mannucci",group:"Peru"},{id:1414,name:"Sport Boys",group:"Peru"},{id:1415,name:"Sporting Cristal",group:"Peru"},{id:1416,name:"Universitario",group:"Peru"},
  // Times - Basket
  {id:1500,name:"Atlanta Dream F",group:"Basquete"},{id:1501,name:"Atlanta Hawks",group:"Basquete"},{id:1502,name:"Basket - Bauru",group:"Basquete"},{id:1503,name:"Basket - Blumenau F",group:"Basquete"},{id:1504,name:"Basket - Brasília",group:"Basquete"},{id:1505,name:"Boston Celtics",group:"Basquete"},{id:1506,name:"Brooklyn Nets",group:"Basquete"},{id:1507,name:"Charlotte Hornets",group:"Basquete"},{id:1508,name:"Chicago Bulls",group:"Basquete"},{id:1509,name:"Cleveland Cavaliers",group:"Basquete"},{id:1510,name:"Dallas Mavericks",group:"Basquete"},{id:1511,name:"Denver Nuggets",group:"Basquete"},{id:1512,name:"Detroit Pistons",group:"Basquete"},{id:1513,name:"Golden State Warriors",group:"Basquete"},{id:1514,name:"Houston Rockets",group:"Basquete"},{id:1515,name:"Indiana Pacers",group:"Basquete"},{id:1516,name:"LA Clippers",group:"Basquete"},{id:1517,name:"LA Lakers",group:"Basquete"},{id:1518,name:"Memphis Grizzlies",group:"Basquete"},{id:1519,name:"Miami Heat",group:"Basquete"},{id:1520,name:"Milwaukee Bucks",group:"Basquete"},{id:1521,name:"Minnesota Timberwolves",group:"Basquete"},{id:1522,name:"New Orleans Pelicans",group:"Basquete"},{id:1523,name:"New York Knicks",group:"Basquete"},{id:1524,name:"Oklahoma City Thunder",group:"Basquete"},{id:1525,name:"Orlando Magic",group:"Basquete"},{id:1526,name:"Philadelphia 76ers",group:"Basquete"},{id:1527,name:"Phoenix Suns",group:"Basquete"},{id:1528,name:"Portland Trail Blazers",group:"Basquete"},{id:1529,name:"Sacramento Kings",group:"Basquete"},{id:1530,name:"San Antonio Spurs",group:"Basquete"},{id:1531,name:"Toronto Raptors",group:"Basquete"},{id:1532,name:"Utah Jazz",group:"Basquete"},{id:1533,name:"Washington Wizards",group:"Basquete"},
  // Times - Vôlei
  {id:1600,name:"Vôlei - ABEL Moda Volei F",group:"Vôlei"},{id:1601,name:"Vôlei - América Vôlei",group:"Vôlei"},{id:1602,name:"Vôlei - Araguari",group:"Vôlei"},{id:1603,name:"Vôlei - Barueri F",group:"Vôlei"},{id:1604,name:"Vôlei - Blumenau",group:"Vôlei"},{id:1605,name:"Vôlei - Brasília",group:"Vôlei"},{id:1606,name:"Vôlei - Cimed",group:"Vôlei"},{id:1607,name:"Vôlei - Cuiabá",group:"Vôlei"},{id:1608,name:"Vôlei - Farroupilha",group:"Vôlei"},{id:1609,name:"Vôlei - Funvic",group:"Vôlei"},{id:1610,name:"Vôlei - Goiás",group:"Vôlei"},{id:1611,name:"Vôlei - Guarulhos",group:"Vôlei"},{id:1612,name:"Vôlei - Sesi",group:"Vôlei"},
];

// GET /api/teams — busca com paginação
router.get('/', authenticate, (req: Request, res: Response) => {
  const search = (req.query.search as string || '').toLowerCase().trim();
  const page   = Math.max(1, parseInt(req.query.page as string) || 1);
  const limit  = Math.min(50, parseInt(req.query.limit as string) || 20);
  const group  = (req.query.group as string || '').trim();

  let results = ALL_TEAMS;

  if (search) {
    results = results.filter(t => t.name.toLowerCase().includes(search));
  }
  if (group) {
    results = results.filter(t => t.group === group);
  }

  const total = results.length;
  const data  = results.slice((page - 1) * limit, page * limit);

  res.json({
    success: true,
    data: {
      teams: data,
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    }
  });
});

// GET /api/teams/groups — lista de grupos
router.get('/groups', authenticate, (_req: Request, res: Response) => {
  const groups = [...new Set(ALL_TEAMS.map(t => t.group))].sort();
  res.json({ success: true, data: groups });
});

export default router;
